### ISSUE TITLE
Using dependent CSLs with pandoc-citeproc?

### ISSUE THREAD

**Issue by tlnagy** [jgm/pandoc-citeproc#105]
I have run into an issue with [dependent CSLs](https://github.com/citation-style-language/styles/tree/master/dependent) and pandoc-citeproc. I think citeproc isn't able to figure out the dependencies of the CSL and leaves all the citations as the **???** placeholders. I tried this with the [bmc-bioinformatics.csl](https://github.com/citation-style-language/styles/blob/master/dependent/bmc-bioinformatics.csl) file.

**Comment by timtylin** [comment]
I think this was fixed a few months ago. What version are you using for pandoc-citeproc?

**Comment by tlnagy** [comment]
I'm using v0.6, which is the latest build available on homebrew.

**Comment by tlnagy** [comment]
I see now that this was closed in #30, but I'm still having problems with it. Maybe support got broken?

**Comment by timtylin** [comment]
That's interesting... it still seems to work on several dependent styles that I've got. Maybe post an example of the CSL that you're trying to use?

**Comment by tlnagy** [comment]
I linked to it in the original post. It's this one: https://github.com/citation-style-language/styles/blob/master/dependent/bmc-bioinformatics.csl

**Comment by timtylin** [comment]
Apologies. I'm checking it now

**Comment by tlnagy** [comment]
No worries. Thanks for looking into it.

**Comment by timtylin** [comment]
I've figured out what broke. It was a bug introduced in the move to `xml-conduit`. Now I'm just wondering why my dependent styles *did* work...

**Comment by timtylin** [comment]
Ah, I was actually in my old scholdoc namespace, so I'm not calling the new citeproc. Mystery solved. Patch incoming.

**Comment by tlnagy** [comment]
Thanks for looking into this! :+1:
